# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ewkiFr_0sYczf1m2Tz6LTEi6dBJKCCbm
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
url="https://raw.githubusercontent.com/erinijapranckeviciene/MLdata/main/Kaggle-data-suic.csv"
data = pd.read_csv(url)

"""Savižudybių skaičiai pasaulyje (1985 - 2016)"""

plt.figure(figsize =(16,8))
sns.lineplot(data = data[data.age == "5-14 years"], x = "year", y = "suicides_no", label = "5-14")
sns.lineplot(data = data[data.age == "15-24 years"], x = "year", y = "suicides_no", label = "15-24")
sns.lineplot(data = data[data.age == "25-34 years"], x = "year", y = "suicides_no", label = "25-34")
sns.lineplot(data = data[data.age == "35-54 years"], x = "year", y = "suicides_no", label = "35-54")
sns.lineplot(data = data[data.age == "55-74 years"], x = "year", y = "suicides_no", label = "55-74")
sns.lineplot(data = data[data.age == "75+ years"], x = "year", y = "suicides_no", label = "75+")
plt.legend(loc = "best")
plt.title("Įvairių amžiaus grupių asmenų savižudybių skaičiai 1985 - 2016")
plt.xlabel("metai")
plt.ylabel("skaičius")

"""Įvairių amžiaus grupių asmenų savižudybių skaičiai 1985 - 2016 kiekvienai šaliai"""

countries = list(set(data.country))
for country in countries:
    plt.figure(figsize =(16,8))
    sns.lineplot(data = data[data.country == country][data.age == "5-14 years"], x = "year", y = "suicides_no", label = "5-14")
    sns.lineplot(data = data[data.country == country][data.age == "15-24 years"], x = "year", y = "suicides_no", label = "15-24")
    sns.lineplot(data = data[data.country == country][data.age == "25-34 years"], x = "year", y = "suicides_no", label = "25-34")
    sns.lineplot(data = data[data.country == country][data.age == "35-54 years"], x = "year", y = "suicides_no", label = "35-54")
    sns.lineplot(data = data[data.country == country][data.age == "55-74 years"], x = "year", y = "suicides_no", label = "55-74")
    sns.lineplot(data = data[data.country == country][data.age == "75+ years"], x = "year", y = "suicides_no", label = "75+")
    plt.legend(loc = "best")
    plt.title("Įvairių amžiaus grupių asmenų savižudybių skaičiai 1985 - 2016 (" + str(country) + ")")
    plt.xlabel("metai")
    plt.ylabel("skaičius")

"""Savižudybių skaičiai pasaulyje pasaulinės finansų krizės metu (2008m)"""

plt.figure(figsize =(16,8))
sns.barplot(data = data[data.year == 2008] , x = "age", y = "suicides_no")
plt.title("Įvairių amžiaus grupių asmenų savižudybių skaičiai 2008 m. (finansų krizė)")
plt.xlabel("amžiaus grupės")
plt.ylabel("skaičius")

"""Savižudybių skaičiai Lietuvoje 1985 - 2016"""

plt.figure(figsize =(16,8))
sns.boxplot(data = data[data.country == "Lithuania"], x = "age", y = "suicides_no")
plt.title("Įvairaus amžiaus grupių savižudybių skaičiai Lietuvoje 1985 - 2016 m.")
plt.xlabel("amžiaus grupės")
plt.ylabel("skaičius")